site_name: SASA Stacker
theme: readthedocs
docs_dir: sources
repo_url: https://github.com/TimLucaTuran/stacker/blob/master/sasa_stacker

nav:
    - Home: index.md
    - Installation: install.md
    - Modules:
        - Fit: fit.md
        - Train: train.md
        - Data Generation: data_gen.md
        - Testing: testing.md
